### ISSUE TITLE
[BUG]: <Dependency Conflicts>

### ISSUE THREAD

**Issue by HighervGround** [surapuramakhil-org/Job_hunt_assistant#29]
### Describe the bug

CREATE_VENV.PIP_FAILED_INSTALL_REQUIREMENTS

### Steps to reproduce

The conflict is caused by:
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.3.1 depends on langchain-core<0.4.0 and >=0.3.27
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.3.0 depends on langchain-core<0.4.0 and >=0.3.17
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.2.4 depends on langchain-core<0.4.0 and >=0.3.15
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.2.3 depends on langchain-core<0.4.0 and >=0.3.9
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.2.1 depends on langchain-core<0.4.0 and >=0.3.1
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.2.0 depends on langchain-core<0.4.0 and >=0.3.0
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.11 depends on langchain-core<0.2.0 and >=0.1.43
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.10 depends on langchain-core<0.2.0 and >=0.1.43
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.9 depends on langchain-core<0.2.0 and >=0.1.43
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.8 depends on langchain-core<0.2.0 and >=0.1.42
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.7 depends on langchain-core<0.2.0 and >=0.1.41
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.6 depends on langchain-core<0.2.0 and >=0.1.33
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.5 depends on langchain-core<0.2.0 and >=0.1.33
    The user requested langchain-core==0
2024-12-29 12:48:13.328 [info] .2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.4 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.3 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.2 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.1 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.1.0 depends on langchain-core<0.2 and >=0.1
    The user requested langchain-core==0.2.36
    langchain 0.2.11 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-community 0.2.10 depends on langchain-core<0.3.0 and >=0.2.23
    langchain-google-genai 1.0.10 depends on langchain-core<0.3 and >=0.2.33
    langchain-ollama 0.1.3 depends on langchain-core<0.3.0 and >=0.2.36
    langchain-openai 0.1.17 depends on langchain-core<0.3.0 and >=0.2.20
    langchain-text-splitters 0.2.2 depends on langchain-core<0.3.0 and >=0.2.10
    lib-resume-builder-aihawk 0.1 depends on langchain-core
    langchain-anthropic 0.0.2 depends on langchain-core<0.2 and >=0.1

### Expected behavior

Successful install of requirements with working dependencies

### Actual behavior

CREATE_VENV.PIP_FAILED_INSTALL_REQUIREMENTS

### Branch

main

### Python version

3.13

### LLM Used

ChatGPT

### Additional context

I finally was able to force the dependencies to play nicely together by tinkering around in requirements.txt; however I also noticed an issue with the Python interpreter being unable to locate the src.job_portals.linkedin module. So the prompt to choose resume style will appear, I select resume style, chrome opens and then immediately closes with the error "unable to locate the src.job_portals.linkedin module"

**Comment by surapuramakhil** [comment]
@HighervGround kindly use release branch release/v0.1.0

It runs on poetry.

**Comment by HighervGround** [comment]
Thanks for the help. What do you mean by branch release/v0.1.0? Sorry I'm a noob...

**Comment by surapuramakhil** [comment]
yes. 

https://github.com/surapuramakhil-org/Job_hunt_assistant/tree/release/v0.1.0

> Sorry I'm a noob... @surapuramakhil
No worries

**Comment by HighervGround** [comment]
I still get "RuntimeError: Error running the bot: No module named 'src.job_portals.linkedIn'"

**Comment by surapuramakhil** [comment]
yes LinkedIn code was removed due to compliance. 

Applying for Lever jobs is more like an alternative (WIP)
https://github.com/surapuramakhil-org/Job_hunt_assistant/pull/30

tracker:
https://github.com/orgs/surapuramakhil-org/projects/1
